# Generated by Django 3.2.3 on 2021-07-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='image',
            field=models.ImageField(blank=True, default='default/def.jpg', null=True, upload_to='articles/', verbose_name='Изображение'),
        ),
    ]
