# Generated by Django 3.2.3 on 2021-06-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='content_type',
            new_name='product',
        ),
    ]
