# Generated by Django 3.2.3 on 2021-06-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_content_type_cartproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='shop.Gloves'),
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
