# Generated by Django 3.2.3 on 2021-05-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_gloves_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='total_products',
            new_name='qty',
        ),
    ]
