# Generated by Django 3.2.3 on 2021-06-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210531_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloves',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Рейтинг'),
        ),
    ]
